export type Block =
  | { type: 'h'; text: string }
  | { type: 'p'; text: string }
  | { type: 'b'; text: string }

export type Article = {
  id: string
  cat: string
  emoji: string
  date: string
  readTime: string
  title: string
  excerpt: string
  blocks: Block[]
}

const h = (text: string): Block => ({ type: 'h', text })
const p = (text: string): Block => ({ type: 'p', text })
const b = (text: string): Block => ({ type: 'b', text })

export const articlesDE: Article[] = [
  {
    id: 'schwangerschaft',
    cat: 'Schwangerschaft',
    emoji: '🤰',
    date: '24. Feb. 2024',
    readTime: '3 Min.',
    title: 'Ernährung während der Schwangerschaft',
    excerpt: 'Warum Folsäure, Eisen und Omega-3 in der Schwangerschaft unverzichtbar sind — und welche Risiken eine unausgewogene Ernährung birgt.',
    blocks: [
      h('Warum muss man besonders auf die Ernährung in der Schwangerschaft achten?'),
      p('Wenn während der Schwangerschaft nicht auf die Ernährung geachtet wird, können verschiedene Risiken für die Gesundheit der Mutter und des Babys auftreten:'),
      b('Entwicklung des Fötus: Eine unzureichende Versorgung mit essentiellen Nährstoffen wie Folsäure, Eisen, Calcium und Omega-3-Fettsäuren kann die normale Entwicklung des Fötus beeinträchtigen und zu angeborenen Anomalien führen.'),
      b('Niedriges Geburtsgewicht: Eine mangelhafte Ernährung und unzureichende Gewichtszunahme können zu einem niedrigen Geburtsgewicht führen, das mit verschiedenen gesundheitlichen Problemen verbunden sein kann.'),
      b('Frühgeburt: Mangelernährung und ungesunde Ernährungsgewohnheiten können das Risiko einer Frühgeburt erhöhen. Frühgeborene Babys haben ein höheres Risiko für Gesundheitsprobleme.'),
      b('Mütterliche Gesundheit: Eine unzureichende Ernährung kann bei der Mutter zu Müdigkeit, Anämie und gestörtem Blutzuckerspiegel führen.'),
      b('Präeklampsie: Eine ungesunde Ernährung kann das Risiko für Präeklampsie erhöhen — eine ernste Schwangerschaftskomplikation mit hohem Blutdruck.'),
      b('Gestationsdiabetes: Eine unausgewogene Ernährung kann das Risiko für Gestationsdiabetes erhöhen, was sowohl für Mutter als auch Baby gesundheitliche Folgen hat.'),
      b('Erhöhtes Infektionsrisiko: Mangelernährung beeinträchtigt das Immunsystem und erhöht die Anfälligkeit für Infektionen.'),
      b('Schlechte Gehirnentwicklung: Ein Mangel an Omega-3-Fettsäuren, insbesondere DHA, kann die normale Entwicklung des Gehirns und des Nervensystems des Babys beeinträchtigen.'),
      b('Verhaltens- und Entwicklungsprobleme: Eine unzureichende Ernährung während der Schwangerschaft kann mit einem erhöhten Risiko für Entwicklungsprobleme beim Kind verbunden sein.'),
      p('Es ist wichtig zu betonen, dass eine gesunde Ernährung während der Schwangerschaft nicht nur Risiken minimiert, sondern auch das Wohlbefinden von Mutter und Kind fördert. Regelmäßige Vorsorgeuntersuchungen und die Zusammenarbeit mit einem Ernährungsexperten sind dringend empfohlen.'),
      h('Empfehlung in der Schwangerschaft'),
      p('Die Ernährung während der Schwangerschaft spielt eine entscheidende Rolle. Hier sind die wichtigsten Punkte:'),
      b('Folsäurezufuhr: Folsäure ist entscheidend für die Entwicklung des Neuralrohrs. Bereits vor der Schwangerschaft supplementieren. Gute Quellen: grünes Blattgemüse, Hülsenfrüchte, angereicherte Lebensmittel.'),
      b('Eisenreiche Ernährung: Der Eisenbedarf steigt während der Schwangerschaft stark an. Gute Quellen: rotes Fleisch, Hülsenfrüchte, Vollkornprodukte, dunkelgrünes Blattgemüse.'),
      b('Calciumzufuhr: Calcium ist wichtig für Knochen und Zähne des Babys. Gute Quellen: Milchprodukte, grünes Blattgemüse, angereicherte Lebensmittel.'),
      b('Proteinreiche Nahrung: Proteine sind entscheidend für das Wachstum von Geweben und Organen. Gute Quellen: mageres Fleisch, Geflügel, Fisch, Eier, Hülsenfrüchte, Nüsse.'),
      b('Omega-3-Fettsäuren: Wichtig für Gehirn- und Augenentwicklung des Babys. Gute Quellen: Lachs, Leinsamen, Walnüsse, Chiasamen.'),
      b('Vitamin D: Wichtig für die Calciumaufnahme und Knochenentwicklung. Quellen: Sonneneinstrahlung, fetter Fisch, Eier, angereicherte Lebensmittel.'),
      b('Rohe Lebensmittel meiden: Rohes Fleisch, rohe Eier und unpasteurisierte Milchprodukte sollten gemieden werden, um Lebensmittelinfektionen zu vermeiden.'),
      b('Koffein und Alkohol begrenzen: Zu viel Koffein erhöht das Fehlgeburtsrisiko. Alkohol sollte vollständig vermieden werden.'),
      b('Kleine, häufige Mahlzeiten: Helfen, Schwangerschaftsübelkeit zu lindern und den Blutzucker stabil zu halten.'),
      b('Gewichtszunahme: Eine angemessene Gewichtszunahme ist wichtig für Mutter und Kind. Die genaue Menge bitte mit dem Arzt besprechen.'),
      p('Individuelle Bedürfnisse variieren. Ein Gespräch mit einem Arzt oder einer Ernährungsfachkraft ist ratsam, um eine auf dich zugeschnittene Ernährungsberatung zu erhalten.'),
    ],
  },
  {
    id: 'aeltere-menschen',
    cat: 'Alltagsernährung',
    emoji: '👴',
    date: '24. Feb. 2024',
    readTime: '2 Min.',
    title: 'Ernährung bei älteren Menschen',
    excerpt: 'Im Alter verändern sich die Ernährungsbedürfnisse. Erfahre, wie du mit der richtigen Ernährung fit und gesund bleibst.',
    blocks: [
      p('Die Ernährung älterer Menschen ist von besonderer Bedeutung, da sich die Ernährungsbedürfnisse im Alter verändern können. Hier sind die wichtigsten Aspekte:'),
      b('Ausreichende Kalorienzufuhr: Ältere Menschen haben oft einen geringeren Energiebedarf, dennoch ist es wichtig, ausreichend Kalorien zu sich zu nehmen, um Muskelmasse und Kraft zu erhalten.'),
      b('Proteinreiche Ernährung: Proteine sind wichtig für die Erhaltung der Muskelmasse und das Immunsystem. Gute Quellen: Fleisch, Fisch, Eier, Milchprodukte, Hülsenfrüchte, Nüsse.'),
      b('Calcium und Vitamin D: Diese Nährstoffe sind entscheidend für die Knochengesundheit. Gute Quellen: Milchprodukte, grünes Blattgemüse, angereicherte Lebensmittel, Sonneneinstrahlung.'),
      b('Ballaststoffreiche Ernährung: Ballaststoffe fördern die Verdauung und helfen, Verstopfung vorzubeugen. Gute Quellen: Vollkornprodukte, Obst, Gemüse, Hülsenfrüchte, Nüsse.'),
      b('Flüssigkeitszufuhr: Ältere Menschen verspüren oft weniger Durst, was zu Dehydration führen kann. Ausreichend Wasser, Kräutertees oder verdünnte Fruchtsäfte sind wichtig.'),
      b('Vitamin B12: Die Aufnahme von Vitamin B12 kann im Alter abnehmen. Es ist wichtig für die Bildung roter Blutkörperchen und das Nervensystem. Gute Quellen: Fleisch, Fisch, Eier, angereicherte Lebensmittel.'),
      b('Salz und gesättigte Fette reduzieren: Eine reduzierte Salzaufnahme hilft, den Blutdruck zu kontrollieren. Weniger gesättigte Fette minimieren das Risiko von Herz-Kreislauf-Erkrankungen.'),
      b('Individuelle Bedürfnisse: Einige ältere Menschen haben besondere Ernährungsbedürfnisse aufgrund von Krankheiten oder Medikamenten. Diese sollten mit einem Arzt besprochen werden.'),
      b('Soziale Aspekte: Mahlzeiten fördern sozialen Zusammenhalt. Regelmäßige Mahlzeiten mit Familie oder Freunden sind wichtig für das Wohlbefinden.'),
      b('Schluckbeschwerden: Ältere Menschen können Schwierigkeiten beim Schlucken haben. Die Konsistenz von Speisen kann entsprechend angepasst werden.'),
      p('Es ist ratsam, regelmäßig Gesundheitschecks durchzuführen und bei Bedarf mit einem Ernährungsexperten zusammenzuarbeiten, um eine individuelle Ernährungsberatung zu erhalten.'),
    ],
  },
  {
    id: 'chronische-muedigkeit',
    cat: 'Alltagsernährung',
    emoji: '⚡',
    date: '24. Feb. 2024',
    readTime: '2 Min.',
    title: 'Ernährung bei chronischer Müdigkeit',
    excerpt: 'Mit der richtigen Ernährung mehr Energie gewinnen — Tipps für einen stabilen Blutzucker und langanhaltende Kraft.',
    blocks: [
      p('Um einen Energie-Boost durch die Ernährung zu erhalten, ist es wichtig, auf eine ausgewogene Ernährung mit bestimmten Nährstoffen zu achten. Hier sind einige Tipps:'),
      b('Komplexe Kohlenhydrate: Wähle Lebensmittel, die den Blutzucker langsam und stabil halten, wie Vollkornprodukte, Haferflocken, Quinoa, Süßkartoffeln und Hülsenfrüchte.'),
      b('Proteine: Wichtig für die Energieproduktion und einen stabilen Blutzucker. Gute Quellen: mageres Fleisch, Fisch, Eier, Milchprodukte, Hülsenfrüchte, Nüsse und Samen.'),
      b('Gesunde Fette: Avocados, Nüsse, Samen und Olivenöl liefern langanhaltende Energie und unterstützen die Aufnahme fettlöslicher Vitamine.'),
      b('Früchte und Gemüse: Liefern wichtige Vitamine, Mineralstoffe und Ballaststoffe, die die Verdauung fördern und den Blutzucker stabilisieren. Besonders empfehlenswert: Beeren, Äpfel, Spinat, Brokkoli.'),
      b('Wasser trinken: Dehydration kann zu Müdigkeit führen. Trinke ausreichend Wasser und koffeinfreie Kräutertees.'),
      b('Kleine, häufige Mahlzeiten: Statt großer Mahlzeiten lieber kleinere, ausgewogene Portionen über den Tag verteilen, um den Blutzucker stabil zu halten.'),
      b('Magnesiumreiche Lebensmittel: Magnesium ist wichtig für die Energieproduktion. Gute Quellen: Spinat, Mandeln, Bananen, Haferflocken.'),
      b('B-Vitamine: B-Vitamine sind direkt an der Energieproduktion beteiligt. Enthalten in: Vollkornprodukten, Fleisch, Fisch, Eiern und grünem Blattgemüse.'),
      b('Stark verarbeitete Lebensmittel meiden: Diese verursachen schnelle Blutzuckerschwankungen und Energietiefs. Bevorzuge natürliche, unverarbeitete Lebensmittel.'),
      b('Täglich bewegen: Regelmäßige körperliche Aktivität kann die Energieproduktion steigern und Müdigkeit langfristig reduzieren.'),
      p('Individuelle Bedürfnisse variieren. Es ist ratsam, sich an einen Ernährungsexperten oder Arzt zu wenden, um persönliche Empfehlungen zu erhalten.'),
    ],
  },
  {
    id: 'stillzeit',
    cat: 'Stillzeit',
    emoji: '🤱',
    date: '24. Feb. 2024',
    readTime: '2 Min.',
    title: 'Ernährung während der Stillzeit',
    excerpt: 'Die Ernährung der Mutter beeinflusst direkt die Qualität der Muttermilch — erfahre, worauf du in der Stillzeit achten solltest.',
    blocks: [
      p('Die Ernährung während der Stillzeit ist wichtig, weil die Mutter über ihre Nahrung die notwendigen Nährstoffe bereitstellen muss, die das heranwachsende Baby für eine gesunde Entwicklung benötigt. Hier sind die wichtigsten Aspekte:'),
      b('Nährstoffversorgung für das Baby: Die Muttermilch ist die Hauptnahrungsquelle für Säuglinge. Eine ausgewogene Ernährung stellt sicher, dass das Baby ausreichend Proteine, Fette, Kohlenhydrate, Vitamine und Mineralstoffe erhält.'),
      b('Gesunde Entwicklung des Babys: Die Ernährung der Mutter beeinflusst die Qualität der Muttermilch und damit die körperliche und geistige Entwicklung des Babys.'),
      b('Energiebedarf der Mutter: Das Stillen erfordert zusätzliche Energie, da der Körper der Mutter Energie für die Milchproduktion benötigt. Eine angemessene Kalorienzufuhr ist daher wichtig.'),
      b('Flüssigkeitszufuhr: Ausreichende Flüssigkeitsaufnahme ist essenziell, um die Milchproduktion aufrechtzuerhalten. Das Stillen erhöht den Flüssigkeitsbedarf — trinke ausreichend Wasser.'),
      b('Vermeidung von Substanzübertragung: Einige Substanzen aus der Nahrung der Mutter können in die Muttermilch übergehen. Alkohol und bestimmte Medikamente sollten daher vermieden werden.'),
      b('Gewichtsmanagement: Das Stillen kann dazu beitragen, schneller zum Ausgangsgewicht zurückzukehren. Eine ausgewogene Ernährung bleibt dennoch wichtig, um die eigene Gesundheit zu unterstützen.'),
      p('Insgesamt ist eine gesunde und ausgewogene Ernährung während der Stillzeit entscheidend, um sowohl die Bedürfnisse des Babys als auch die der Mutter zu erfüllen. Es wird empfohlen, mit einem Gesundheitsdienstleister oder Ernährungsberater zu sprechen.'),
    ],
  },
  {
    id: 'gehirn',
    cat: 'Mentale Gesundheit',
    emoji: '🧠',
    date: '24. Feb. 2024',
    readTime: '2 Min.',
    title: 'Wie man sein Gehirn ernährt',
    excerpt: 'Das Gehirn braucht die richtigen Nährstoffe — erfahre, wie Omega-3, Antioxidantien und B-Vitamine die Gehirngesundheit fördern.',
    blocks: [
      p('Die richtige Ernährung spielt eine wichtige Rolle für die Gesundheit des Gehirns. Hier sind die wichtigsten Tipps, wie man das Gehirn optimal ernähren kann:'),
      b('Omega-3-Fettsäuren: Diese essentiellen Fettsäuren sind wichtig für die Gehirnfunktion. Gute Quellen: fetter Fisch (Lachs, Makrele, Hering), Leinsamen, Walnüsse, Chiasamen.'),
      b('Antioxidantien: Eine vielfältige Auswahl an Obst und Gemüse schützt die Gehirnzellen vor oxidativem Stress. Besonders empfehlenswert: Beeren, grünes Blattgemüse, Tomaten, Karotten.'),
      b('Vitamine und Mineralstoffe: B-Vitamine (B6, B12, Folsäure), Vitamin E und D sowie Mineralstoffe wie Eisen, Zink und Magnesium sind wichtig für die Gehirngesundheit.'),
      b('Gute Kohlenhydrate: Komplexe Kohlenhydrate wie Vollkornprodukte, Quinoa, Haferflocken und Hülsenfrüchte liefern langanhaltende Energie für das Gehirn.'),
      b('Proteine: Wichtig für die Bildung von Neurotransmittern, die die Kommunikation zwischen Gehirnzellen unterstützen. Gute Quellen: Fisch, Geflügel, mageres Fleisch, Hülsenfrüchte, Nüsse.'),
      b('Hydratation: Ausreichendes Trinken ist entscheidend für die Gehirngesundheit — Dehydration beeinträchtigt die kognitive Leistungsfähigkeit spürbar.'),
      b('Zucker und gesättigte Fette in Maßen: Ein übermäßiger Verzehr kann negative Auswirkungen auf die Gehirngesundheit haben.'),
      p('Eine ausgewogene Ernährung ist nur ein Teil des Gesamtpakets für die Gehirngesundheit. Regelmäßige körperliche Aktivität, ausreichend Schlaf und geistige Stimulation sind ebenfalls entscheidend. Bei speziellen gesundheitlichen Anliegen ist ein Arzt oder Ernährungsberater zu empfehlen.'),
    ],
  },
  {
    id: 'sportler',
    cat: 'Sport & Fitness',
    emoji: '🏃',
    date: '24. Feb. 2024',
    readTime: '2 Min.',
    title: 'Ernährung bei Sportlern',
    excerpt: 'Sportler haben besondere Ernährungsbedürfnisse — erfahre, wie du Leistung, Erholung und Gesundheit gezielt optimierst.',
    blocks: [
      h('Warum muss man als Sportler besonders auf die Ernährung achten?'),
      b('Energiebedarf: Sportliche Aktivitäten bedingen einen erhöhten Energieverbrauch. Eine ausgewogene Ernährung stellt sicher, dass der Körper genügend Kalorien erhält.'),
      b('Leistungsoptimierung: Kohlenhydrate, Proteine und Fette sind entscheidende Makronährstoffe, die dem Körper Energie zuführen und die muskuläre Leistungsfähigkeit fördern.'),
      b('Erholung und Regeneration: Proteine fördern den Muskelaufbau und reparieren geschädigtes Gewebe, während Kohlenhydrate die Energiereserven nach dem Training wieder auffüllen.'),
      b('Verletzungsprävention: Eine ausgewogene Ernährung mit Vitaminen und Mineralstoffen trägt dazu bei, Knochen, Muskeln und Gelenke gesund zu halten.'),
      b('Hydratation: Sportler verlieren durch Schwitzen Flüssigkeit und Elektrolyte. Ausreichende Flüssigkeitszufuhr verhindert Leistungsabfall und Hitzestress.'),
      b('Gewichtsmanagement: Die richtige Ernährung unterstützt Sportler dabei, ihre Gewichtsziele zu erreichen — ob Gewichtsabnahme, -erhaltung oder -zunahme.'),
      b('Immunsystemstärkung: Eine ausgewogene Versorgung mit Vitaminen und Mineralstoffen stärkt das Immunsystem und beugt Infektionen vor.'),
      b('Individuelle Anpassung: Die Ernährungsanforderungen variieren je nach Sportart, Intensität, Dauer, Geschlecht, Alter und persönlichen Zielen.'),
      h('Wie kann ich mich als Sportler ernähren?'),
      b('Ausreichende Kalorienzufuhr: Sportler benötigen zusätzliche Kalorien. Die genaue Menge hängt von Aktivität, Intensität, Körpergewicht und Stoffwechsel ab.'),
      b('Ausgewogene Makronährstoffe: Eine ausgewogene Zufuhr von Proteinen, Kohlenhydraten und gesunden Fetten ist entscheidend für Muskelaufbau, Energie und Erholung.'),
      b('Proteinquellen: Mageres Fleisch, Fisch, Geflügel, Eier, Milchprodukte, Hülsenfrüchte und Nüsse sichern eine ausreichende Proteinzufuhr.'),
      b('Kohlenhydrate vor dem Training: Kohlenhydratreiche Mahlzeiten vor dem Training füllen die Glykogenspeicher und steigern die Leistung.'),
      b('Protein nach dem Training: Eine proteinreiche Mahlzeit oder ein Proteinshake nach dem Training unterstützt die Muskelregeneration.'),
      b('Gesunde Fette: Avocados, Nüsse, Samen und Olivenöl liefern essentielle Fettsäuren und fördern die allgemeine Gesundheit.'),
      b('Vitamine und Mineralstoffe: Durch Obst, Gemüse, Vollkornprodukte und nährstoffreiche Lebensmittel ausreichend versorgen.'),
      b('Hydratation: Den Flüssigkeitsverlust durch Schwitzen ausgleichen. Der Bedarf variiert je nach Aktivität und Umgebung.'),
      b('Timing der Mahlzeiten: Mahlzeiten und Snacks so planen, dass genug Energie für das Training und eine optimale Erholung danach vorhanden ist.'),
      p('Es ist ratsam, sich von einem Ernährungsexperten oder Sporternährungsberater beraten zu lassen, um einen maßgeschneiderten Ernährungsplan zu erstellen.'),
    ],
  },
  {
    id: 'muskelaufbau',
    cat: 'Sport & Fitness',
    emoji: '💪',
    date: '24. Feb. 2024',
    readTime: '3 Min.',
    title: 'Muskelaufbau',
    excerpt: 'Muskeln aufbauen geht nicht ohne die richtige Ernährung — erfahre, was du essen solltest und wie Training und Ernährung zusammenspielen.',
    blocks: [
      h('Was bedeutet Muskelaufbau?'),
      p('Muskelaufbau beschreibt den Prozess, durch den gezieltes Training und eine angemessene Ernährung zur Vergrößerung der Muskulatur führen. Typischerweise wird Muskelaufbau durch Krafttraining erreicht, bei dem Muskeln gegen einen Widerstand arbeiten und dabei mikroskopisch kleine Verletzungen entstehen. Während der Erholungsphase reparieren sich diese Verletzungen, wodurch die Muskelfasern größer und stärker werden.'),
      p('Eine ausgewogene Ernährung mit ausreichend Proteinen, Kohlenhydraten und gesunden Fetten ist dabei entscheidend, da Proteine die Bausteine für Muskeln sind.'),
      h('Was sind die Vorteile von Muskelaufbau?'),
      b('Erhöhte Stoffwechselrate: Muskulatur verbrennt mehr Kalorien als Fettgewebe, was den Grundumsatz erhöht und beim Gewichtsmanagement hilft.'),
      b('Bessere Körperkontur: Gut entwickelte Muskulatur verbessert die Körperform und wird häufig als ästhetisch ansprechend empfunden.'),
      b('Stärkung des Bewegungsapparats: Starke Muskeln stützen Gelenke und Knochen und reduzieren das Verletzungsrisiko.'),
      b('Verbesserte Körperhaltung: Gut entwickelte Muskulatur verbessert die Körperhaltung und beugt Rückenschmerzen vor.'),
      b('Gesteigerte körperliche Leistung: Mehr Kraft und Ausdauer steigern die Leistungsfähigkeit bei Sport und im Alltag.'),
      b('Stoffwechselgesundheit: Muskeln spielen eine Rolle bei der Regulation des Blutzuckers und können Diabetes vorbeugen.'),
      b('Steigerung der Knochendichte: Krafttraining fördert die Knochendichte und reduziert das Risiko von Osteoporose.'),
      b('Verbesserte Insulinsensitivität: Muskelaufbau verbessert die Insulinsensitivität und unterstützt die Blutzuckerkontrolle.'),
      b('Psychologische Vorteile: Muskelaufbau kann das Selbstbewusstsein stärken und zur Stressreduktion beitragen.'),
      b('Verlangsamung des Alterungsprozesses: Gut erhaltene Muskulatur verlangsamt den altersbedingten Abbau von Muskelmasse und Funktionen.'),
      h('Was kann man tun, um Muskeln aufzubauen?'),
      b('Krafttraining: Regelmäßig Kraft- oder Widerstandstraining durchführen — mit Gewichten, Widerstandsbändern oder dem eigenen Körpergewicht.'),
      b('Progressive Überlastung: Die Trainingsintensität schrittweise steigern, indem Last oder Wiederholungen erhöht werden, um Muskelwachstum zu fördern.'),
      b('Proteinreiche Ernährung: Auf eine ausreichende Proteinzufuhr achten. Gute Quellen: Fleisch, Fisch, Eier, Milchprodukte, Hülsenfrüchte, Nüsse.'),
      b('Ausgewogene Ernährung: Neben Proteinen auch Kohlenhydrate, gesunde Fette, Vitamine und Mineralstoffe sicherstellen.'),
      b('Ausreichende Kalorienzufuhr: Für den Muskelaufbau benötigt der Körper zusätzliche Energie. Genug Kalorien konsumieren, um diesen Bedarf zu decken.'),
      b('Ausreichende Erholung: Den Muskeln genug Zeit zur Erholung geben. Ausreichend Schlaf und Ruhepausen sind entscheidend.'),
      b('Hydratation: Ausreichende Flüssigkeitszufuhr ist sowohl für den Muskelaufbau als auch für die allgemeine Gesundheit wichtig.'),
      b('Konsistenz: An den Trainings- und Ernährungsplan halten. Muskelaufbau braucht Zeit und kontinuierliche Anstrengung.'),
      b('Variation im Training: Verschiedene Übungen und Trainingsmethoden integrieren, um unterschiedliche Muskelgruppen zu beanspruchen und Plateaus zu vermeiden.'),
      p('Individuelle Ergebnisse können variieren. Vor Beginn eines neuen Fitnessprogramms ist die Konsultation eines Arztes ratsam, insbesondere bei gesundheitlichen Bedenken.'),
    ],
  },
  {
    id: 'masse-aufbauen',
    cat: 'Sport & Fitness',
    emoji: '⚖️',
    date: '24. Feb. 2024',
    readTime: '3 Min.',
    title: 'Gesund Masse aufbauen',
    excerpt: 'Gewicht zuzunehmen kann gesund sein — erfahre, wie du auf natürliche Weise Muskelmasse aufbaust, ohne dabei unnötig Fett anzusetzen.',
    blocks: [
      h('Was ist eine gesunde Gewichtszunahme?'),
      p('Eine gesunde Gewichtszunahme bezeichnet die stufenweise und nachhaltige Erhöhung des Körpergewichts mit dem Ziel, das Wohlbefinden zu fördern und gesundheitliche Risiken zu minimieren. Der Fokus liegt dabei darauf, zusätzliches Gewicht in Form von Muskelmasse zu gewinnen und nicht ausschließlich in Form von Fett.'),
      h('Was sind die Vorteile einer Gewichtszunahme?'),
      b('Steigerung des Selbstwertgefühls: Eine gesunde Gewichtszunahme, besonders durch Muskelaufbau, stärkt das körperliche Wohlbefinden, das Selbstbewusstsein und fördert eine positive Körperwahrnehmung.'),
      b('Verbesserter Gesundheitszustand: Eine ausgewogene Gewichtszunahme kann den allgemeinen Gesundheitszustand verbessern, indem sie die Körperfunktionen optimiert und das Immunsystem stärkt.'),
      b('Erhöhte Muskelmasse: Gezielte Gewichtszunahme in Form von Muskelmasse steigert die körperliche Leistungsfähigkeit und Kraft.'),
      b('Energiestabilisierung: Zusätzliche Kalorien können dazu beitragen, einen stabilen Energiehaushalt aufrechtzuerhalten und die Lebensqualität zu verbessern.'),
      b('Bessere Nährstoffversorgung: Mit einer höheren Kalorienaufnahme kann auch die Zufuhr von essentiellen Vitaminen und Mineralstoffen verbessert werden.'),
      b('Hormonelle Regulation: Ein ausgewogenes Gewicht kann hormonelle Ungleichgewichte minimieren und positive Auswirkungen auf verschiedene Körperfunktionen haben.'),
      h('Was kann man tun, um gesund zuzunehmen?'),
      b('Ausgewogene Ernährung: Nährstoffreiche Lebensmittel wählen, die eine Vielzahl von Vitaminen, Mineralstoffen und Makronährstoffen bieten — mit gesunden Fetten, Proteinen und komplexen Kohlenhydraten.'),
      b('Häufigere Mahlzeiten: Die Anzahl der Mahlzeiten und Snacks über den Tag erhöhen, um die Gesamtkalorienaufnahme zu steigern. Kleine, proteinreiche und kalorienreiche Snacks wählen.'),
      b('Proteinreiches Essen: Proteinreiche Lebensmittel wie mageres Fleisch, Fisch, Eier, Hülsenfrüchte und Milchprodukte in die Ernährung integrieren, um den Muskelaufbau zu unterstützen.'),
      b('Krafttraining: Die Ernährung durch regelmäßiges Krafttraining ergänzen. Ein Fitnesstrainer kann einen individuell angepassten Trainingsplan erstellen.'),
      b('Gesunde Fette: Gesunde Fette aus Avocados, Nüssen, Samen und Olivenöl liefern zusätzliche Kalorien und essentielle Nährstoffe.'),
      b('Leere Kalorien vermeiden: Zusätzliche Kalorien sollten aus nährstoffreichen Quellen stammen. Stark verarbeitete Lebensmittel mit geringem Nährwert meiden.'),
      p('Individuelle Bedürfnisse variieren. Ein Gespräch mit einem Arzt oder einer Ernährungsfachkraft ist ratsam, um eine auf dich zugeschnittene Beratung zu erhalten.'),
    ],
  },
  {
    id: 'gewichtsabnahme',
    cat: 'Alltagsernährung',
    emoji: '🥗',
    date: '9. Jan. 2024',
    readTime: '2 Min.',
    title: 'Gewichtsabnahme',
    excerpt: 'Gewicht zu verlieren ist mehr als nur Kalorien zählen — erfahre, wie eine ganzheitliche Herangehensweise nachhaltige Ergebnisse bringt.',
    blocks: [
      p('Die Gewichtsabnahme ist ein Prozess, bei dem eine Person absichtlich Körpergewicht reduziert, oft mit dem Ziel, die Gesundheit zu verbessern oder persönliche Ziele zu erreichen. Die Vorteile gehen dabei weit über das rein Äußerliche hinaus.'),
      h('Was ist Gewichtsabnahme?'),
      p('Gewichtsabnahme bezeichnet den Verlust von Körpermasse durch eine negative Energiebilanz — die aufgenommene Energie ist geringer als die verbrauchte. Die Reduzierung von Körperfett ist dabei oft das Hauptziel. Dieser Prozess kann durch eine gesunde Ernährung, körperliche Aktivität und manchmal medizinische Interventionen erreicht werden.'),
      h('Mögliche Nachteile des Übergewichts'),
      b('Gesundheitsprobleme: Übergewicht erhöht das Risiko für Herzkrankheiten, Diabetes, Bluthochdruck und bestimmte Krebsarten.'),
      b('Bewegungseinschränkungen: Übergewicht kann zu eingeschränkter Mobilität und Gelenkbelastung führen.'),
      b('Psychische Belastung: Geringes Selbstwertgefühl, Depressionen und soziale Stigmatisierung können auftreten.'),
      b('Schlafprobleme: Übergewicht kann zu Schlafapnoe und anderen Schlafstörungen führen.'),
      b('Atemprobleme: Zusätzliches Gewicht kann auf Brust und Atemwege drücken und zu Atemproblemen führen.'),
      b('Hormonelle Ungleichgewichte: Übergewicht kann den Stoffwechsel und andere Körperfunktionen beeinträchtigen.'),
      b('Erhöhtes Risiko für Fettleber: Übergewicht kann zu Fettlebererkrankungen führen, die die Leberfunktion langfristig schädigen.'),
      h('Vorteile der Gewichtsabnahme'),
      p('Gewichtsabnahme kann eine Vielzahl von gesundheitlichen Vorteilen bringen. Ein gesundes Gewicht verbessert die Herzgesundheit und reduziert das Risiko von Herzkrankheiten und Bluthochdruck. Zudem verbessert sich die Blutzuckerkontrolle, was besonders für Menschen mit Diabetes bedeutsam ist. Gelenkprobleme werden durch weniger Körpergewicht ebenfalls verringert — bei Arthritis kann dies zu spürbar weniger Schmerzen und besserer Beweglichkeit führen.'),
      h('Was kann man tun, um Gewicht abzunehmen?'),
      p('Eine ausgewogene Ernährung reich an Obst, Gemüse, magerem Protein und Vollkornprodukten bildet die Grundlage. Die Kalorienaufnahme zu kontrollieren und nachhaltig abzunehmen ist wichtiger als schnelle Lösungen.'),
      p('Regelmäßige körperliche Aktivität spielt eine entscheidende Rolle. Sowohl aerobe Übungen wie Laufen oder Schwimmen als auch Krafttraining helfen, Fett zu verbrennen und Muskelmasse zu erhalten.'),
      p('Zusätzlich kann die Unterstützung durch Ernährungsberater oder Fitness-Coaches hilfreich sein. Medizinische Interventionen sollten immer unter Anleitung von Gesundheitsdienstleistern erfolgen.'),
      p('Gewichtsabnahme ist individuell — nicht jeder Körper reagiert gleich. Die Konsultation mit einem Gesundheitsdienstleister vor Beginn eines Gewichtsabnahme-Plans ist ratsam.'),
    ],
  },
]

// French articles - same structure, content to be translated
export const articlesFR: Article[] = articlesDE.map(a => ({ ...a }))
